name: inference-pipeline

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  inference-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies
        run: poetry install 
      - name: Execute python workflow
        env:
         HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
         HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
         COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
         COMET_WORKSPACE_NAME: ${{ secrets.COMET_WORKSPACE_NAME }}
        run: poetry run python inference_pipeline/src/main.py
